theme: jekyll-theme-minimal

title: Hi, I'm Rui Qin Ng!
description: Welcome to my Website.

sidebar:
    - title: "Data Analytics Projects"
      url: "analytics-projects.html"
    - title: "Software Engineering Projects"
      url: "software-projects.html"
    - title: "View My LinkedIn Profile"
      url: "https://www.linkedin.com/in/ngrq94/"