theme: jekyll-theme-minimal

title: Rui Qin Ng
description: Welcome to my Website.

sidebar:
    - title: "My Resume"
      url: "assets/Ng Rui Qin_Resume.pdf"
    - title: "Data Analytics Projects"
      url: "analytics-projects.html"
    - title: "Software Engineering Projects"
      url: "software-projects.html"
    - title: "View My LinkedIn Profile"
      url: "https://www.linkedin.com/in/ngrq94/"